
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      password: MyStrongPassword123

server:
  port: 0
#	logging.level.net.javacrumbs.shedlock=DEBUG


logging:
  level:
    '[net.javacrumbs.shedlock.spring.aop]': DEBUG
    '[net.javacrumbs.shedlock]': DEBUG


